modLoader="javafml"
loaderVersion="[43,)"

license="MIT License"

[[mods]]
modId="zeldamod"
version="1.4.2"
displayName="Legendary Armory"

logoFile= "../0.png"

credits="KaupenJoe for his amazing tutorial series"
authors="Kamtheman56"
description='''
Enjoy an epic quest with legendary items and adventures. The best Zelda mod there is!
'''

[[dependencies.zeldamod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zeldamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.22)"
    ordering="NONE"
    side="BOTH"
